import MainLayout from "@/app/main";
import ErrorPage from "@/common/layouts/ErrorPage";
import { APP_CONFIG } from "@/config/app.config";
import { API_CODE, API_METHOD_ENUM } from "@/enums/api.enum";
import { APP_AUTH } from "@/enums/app.enum";
import { catchError, responseError } from "@/services/base.service";
import TaskDetailView from "@/views/task/detail/TaskDetailView";
import { Metadata } from "next";
import { cookies } from "next/headers";
import React, { use } from "react";
import '../../../../../../css/pages/task_detail.css';
import { BaseResponseType } from "@/types/base.type";
import { TaskType } from "@/types/task.type";

interface TaskDetailPageProps {
  params: {
    id: number,
    project_id: number,
    task_id: number
  }
}

export const metadata: Metadata = {
  title: "Next Ticket | Task",
  description: "Generated by Pham Van Chien - phamvanchien3605@gmail.com - Projects",
};

const TaskDetailPage: React.FC<TaskDetailPageProps> = ({ params }) => {
  const task = use(fetchTask(params.id, params.project_id, params.task_id));
  if (!task || task.code !== API_CODE.OK) {
    return <ErrorPage errorCode={task.code} />
  }
  return <MainLayout workspace={task.data.workspace}>
    <TaskDetailView task={task.data} />
  </MainLayout>
}

const fetchTask = async (
  workspaceId: number, 
  projectId: number, 
  taskId: number
): Promise<BaseResponseType<TaskType>> => {
  try {
    const apiResponse = await fetch(
      APP_CONFIG.API.URL + APP_CONFIG.API.PREFIX.task.url + '/' + workspaceId.toString() + '/' + projectId.toString() + '/' + taskId.toString(), {
      method: API_METHOD_ENUM.GET,
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${cookies().get(APP_AUTH.COOKIE_AUTH_KEY)?.value}`
      }
    });
  
    return await apiResponse.json();
  } catch (error) {
    const errorRes = responseError(500);
    errorRes.error = catchError();
    return errorRes;
  }
};

export default TaskDetailPage;