import DocumentView from "@/views/document/DocumentView";
import { Metadata } from "next";
import React from "react";
import '../../../../app/css/pages/document.css';

export const metadata: Metadata = {
  title: "Next Ticket | Documents",
  description: "Generated by Pham Van Chien - phamvanchien3605@gmail.com - Documents",
};

interface DocumentPageProps {
  params: { id: number };
}

const DocumentPage: React.FC<DocumentPageProps> = ({ params }) => {
  return <DocumentView workspaceId={params.id} />
}
export default DocumentPage;