import DocumentCreateView from "@/views/document/DocumentCreateView";
import { Metadata } from "next";
import '../../../../css/pages/document.css';
import React from "react";

export const metadata: Metadata = {
  title: "Next Ticket | Documents",
  description: "Generated by Pham Van Chien - phamvanchien3605@gmail.com - Documents",
};

interface CreateDocumentPageProps {
  params: { id: number };
}

const CreateDocumentPage: React.FC<CreateDocumentPageProps> = ({ params }) => {
  return <DocumentCreateView workspaceId={params.id} />
}
export default CreateDocumentPage;