import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./css/adminlte.min.css";
import '@fortawesome/fontawesome-svg-core/styles.css';
import './css/style.css';
import './css/system.css';
import BodyLayout from "./body";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Ticket",
  description: "Generated by Pham Van Chien - phamvanchien3605@gmail.com",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <BodyLayout>
          {children}
        </BodyLayout>
      </body>
    </html>
  );
}
