import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./css/adminlte.min.css";
import '@fortawesome/fontawesome-svg-core/styles.css';
import './css/style.css';
import './css/system.css';
import BodyLayout from "./body";
import {NextIntlClientProvider} from 'next-intl';
import { headers } from "next/headers";
import { defaultLocale } from "@/next-intl-config";
import { getLocale } from "next-intl/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Ticket",
  description: "Generated by Pham Van Chien - phamvanchien3605@gmail.com",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = headers().get('locale') || defaultLocale;
  console.log('locale: ', locale)
  const messages = require(`@/locales/${locale}.json`);
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <BodyLayout>
          <NextIntlClientProvider locale={locale} messages={messages}>
            {children}
          </NextIntlClientProvider>
        </BodyLayout>
      </body>
    </html>
  );
}
