import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./css/adminlte.min.css";
import '@fortawesome/fontawesome-svg-core/styles.css';
import './css/style.css';
import './css/system.css';
import BodyLayout from "./body";
import {NextIntlClientProvider} from 'next-intl';
import { headers } from "next/headers";
import { defaultLocale } from "@/next-intl-config";
import React from "react";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Tech",
  description: "Generated by Pham Van Chien - phamvanchien3605@gmail.com",
  openGraph: {
    title: "Next Tech",
    description: "Generated by Pham Van Chien - phamvanchien3605@gmail.com",
    url: "https://yourwebsite.com",
    siteName: "Next Tech",
    images: [
      {
        url: "/img/logo-2.png",  // Đường dẫn ảnh (tốt nhất dùng ảnh public)
        width: 1200,
        height: 630,
        alt: "Next Tech Meta Image",
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Next Tech",
    description: "Generated by Pham Van Chien - phamvanchien3605@gmail.com",
    images: ["/img/logo-2.png"], // Ảnh Twitter Card
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = headers().get('locale') || defaultLocale;
  const messages = require(`@/locales/${locale}.json`);
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true}>
        <BodyLayout>
          <NextIntlClientProvider locale={locale} messages={messages}>
            {children}
          </NextIntlClientProvider>
        </BodyLayout>
      </body>
    </html>
  );
}
