import ProfileView from "@/views/profile/ProfileView";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next Ticket | Profile",
  description: "Generated by Pham Van Chien - phamvanchien3605@gmail.com - Profile",
};

const ProfilePage = () => {
  return <ProfileView />
}
export default ProfilePage;