import ProfileUserView from "@/views/profile-user/ProfileUserView";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Next Ticket | Profile",
  description: "Generated by Pham Van Chien - phamvanchien3605@gmail.com - Profile",
};

interface ProfileUserPageProps {
  params: {
    id: number;
  };
}

const ProfileUserPage: React.FC<ProfileUserPageProps> = ({ params }) => {
  return <ProfileUserView userId={params.id} />
}
export default ProfileUserPage;