import AuthLayout from "@/common/layouts/AuthLayout";
import LoginView from "@/views/login/LoginView";
import { Metadata } from "next";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Next Ticket | Login",
  description: "Generated by Pham Van Chien - phamvanchien3605@gmail.com - Login",
};

const LoginPage = () => {
  return <Suspense>
    <LoginView />
  </Suspense>
};
LoginPage.getLayout = (page: React.ReactNode) => <AuthLayout>{page}</AuthLayout>;
export default LoginPage;
