import { Suspense } from 'react';
import '../css/pages/auth.css';
import LoginView from "@/views/login/LoginView";
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Next Ticket | Login",
  description: "Generated by Pham Van Chien - phamvanchien3605@gmail.com - Login",
};

const LoginPage = () => {
  return <Suspense>
    <LoginView />
  </Suspense>
}
export default LoginPage;