import RecentView from "@/views/recent/RecentView";
import { Metadata } from "next";
import React from "react";
import '../../../css/pages/recent.css';

export const metadata: Metadata = {
  title: "Next Ticket | Workspace recent",
  description: "Generated by Pham Van Chien - phamvanchien3605@gmail.com - Workspace recent",
};

interface RecentPageProps {
  params: { 
    id: number
  };
}

const RecentPage: React.FC<RecentPageProps> = ({ params }) => {
  return <RecentView workspaceId={params.id} />
}
export default RecentPage;