import ProjectView from "@/views/project/ProjectView";
import MainLayout from "@/app/main";
import ErrorPage from "@/common/layouts/ErrorPage";
import { APP_CONFIG } from "@/config/app.config";
import { API_CODE, API_METHOD_ENUM } from "@/enums/api.enum";
import { cookies } from "next/headers";
import React, { use } from "react";
import '../../../css/pages/project.css';
import { catchError, responseError } from "@/services/base.service";
import { Metadata } from "next";
import { APP_AUTH } from "@/enums/app.enum";
import { BaseResponseType } from "@/types/base.type";
import { WorkspaceType } from "@/types/workspace.type";

interface ProjectPageProps {
  params: {
    id: number
  }
}

export const metadata: Metadata = {
  title: "Next Ticket | Projects",
  description: "Generated by Pham Van Chien - phamvanchien3605@gmail.com - Projects",
};

const ProjectPage: React.FC<ProjectPageProps> = ({ params }) => {
  const workspace = use(fetchWorkspace(params.id));
  if (!workspace || workspace.code !== API_CODE.OK) {
    return <ErrorPage errorCode={workspace.code} />
  }

  return <MainLayout workspace={workspace.data}>
    <ProjectView workspace={workspace.data} />
  </MainLayout>
}

const fetchWorkspace = async (workspaceId: number): Promise<BaseResponseType<WorkspaceType>> => {
  try {
    const apiResponse = await fetch(APP_CONFIG.API.URL + APP_CONFIG.API.PREFIX.workspace.url + '/' + workspaceId.toString(), {
      method: API_METHOD_ENUM.GET,
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${cookies().get(APP_AUTH.COOKIE_AUTH_KEY)?.value}`
      }
    });
    
    return await apiResponse.json();
  } catch (error) {
    const errorRes = responseError(500);
    errorRes.error = catchError();
    return errorRes;
  }
};

export default ProjectPage;