import ProjectView from "@/views/project/ProjectView";
import '../../../css/pages/project.css';
import '../../../css/pages/workspace.css';
import React from "react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next Ticket | Projects",
  description: "Generated by Pham Van Chien - phamvanchien3605@gmail.com - Projects",
};

interface ProjectPageProps {
  params: { id: number };
}

const ProjectPage: React.FC<ProjectPageProps> = ({ params }) => {
  return <ProjectView workspaceId={params.id} />
}
export default ProjectPage;