import WorkspaceView from "@/views/workspace/WorkspaceView"
import { Metadata } from "next";
import '../css/pages/workspace.css';

export const metadata: Metadata = {
  title: "Next Ticket | Workspaces",
  description: "Generated by Pham Van Chien - phamvanchien3605@gmail.com - Workspaces",
};

const WorkspacePage = () => {
  return <WorkspaceView />
}
export default WorkspacePage;